language: go

go:
  - 1.2

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install libffi-dev -qq

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
